[prune]
  go-tests = true
  unused-packages = true

# CLI interface
[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

# Configuration storage
[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.3.2"
[[constraint]]
  name = "github.com/mitchellh/go-homedir"
  version = "1.1.0"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "^1.3.0"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.19.0"

[[constraint]]
  branch = "master"
  name = "github.com/mholt/certmagic"

# For validating DNS/hostnames
[[constraint]]
  branch = "master"
  name = "github.com/bobesa/go-domain-util"

# Testing
[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.3.0"
