// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Request for a certificate to be issued
type CertificateRequest struct {
	// Example: foo.bar.com
	DnsName              string   `protobuf:"bytes,1,opt,name=dnsName,proto3" json:"dnsName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CertificateRequest) Reset()         { *m = CertificateRequest{} }
func (m *CertificateRequest) String() string { return proto.CompactTextString(m) }
func (*CertificateRequest) ProtoMessage()    {}
func (*CertificateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *CertificateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CertificateRequest.Unmarshal(m, b)
}
func (m *CertificateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CertificateRequest.Marshal(b, m, deterministic)
}
func (m *CertificateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CertificateRequest.Merge(m, src)
}
func (m *CertificateRequest) XXX_Size() int {
	return xxx_messageInfo_CertificateRequest.Size(m)
}
func (m *CertificateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CertificateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CertificateRequest proto.InternalMessageInfo

func (m *CertificateRequest) GetDnsName() string {
	if m != nil {
		return m.DnsName
	}
	return ""
}

// A successful response containing a issued certificate
type CertificateResponse struct {
	// A blob containing the cert
	Certificate string `protobuf:"bytes,1,opt,name=certificate,proto3" json:"certificate,omitempty"`
	// A blob containing the private key
	PrivateKey string `protobuf:"bytes,2,opt,name=privateKey,proto3" json:"privateKey,omitempty"`
	// The DNS names this certificate is valid for
	Names                []string `protobuf:"bytes,3,rep,name=names,proto3" json:"names,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CertificateResponse) Reset()         { *m = CertificateResponse{} }
func (m *CertificateResponse) String() string { return proto.CompactTextString(m) }
func (*CertificateResponse) ProtoMessage()    {}
func (*CertificateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *CertificateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CertificateResponse.Unmarshal(m, b)
}
func (m *CertificateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CertificateResponse.Marshal(b, m, deterministic)
}
func (m *CertificateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CertificateResponse.Merge(m, src)
}
func (m *CertificateResponse) XXX_Size() int {
	return xxx_messageInfo_CertificateResponse.Size(m)
}
func (m *CertificateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CertificateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CertificateResponse proto.InternalMessageInfo

func (m *CertificateResponse) GetCertificate() string {
	if m != nil {
		return m.Certificate
	}
	return ""
}

func (m *CertificateResponse) GetPrivateKey() string {
	if m != nil {
		return m.PrivateKey
	}
	return ""
}

func (m *CertificateResponse) GetNames() []string {
	if m != nil {
		return m.Names
	}
	return nil
}

// A request for ping
type PingRequest struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingRequest) Reset()         { *m = PingRequest{} }
func (m *PingRequest) String() string { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()    {}
func (*PingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *PingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingRequest.Unmarshal(m, b)
}
func (m *PingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingRequest.Marshal(b, m, deterministic)
}
func (m *PingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingRequest.Merge(m, src)
}
func (m *PingRequest) XXX_Size() int {
	return xxx_messageInfo_PingRequest.Size(m)
}
func (m *PingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PingRequest proto.InternalMessageInfo

func (m *PingRequest) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

// A response for ping
type PingResponse struct {
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingResponse) Reset()         { *m = PingResponse{} }
func (m *PingResponse) String() string { return proto.CompactTextString(m) }
func (*PingResponse) ProtoMessage()    {}
func (*PingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *PingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingResponse.Unmarshal(m, b)
}
func (m *PingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingResponse.Marshal(b, m, deterministic)
}
func (m *PingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingResponse.Merge(m, src)
}
func (m *PingResponse) XXX_Size() int {
	return xxx_messageInfo_PingResponse.Size(m)
}
func (m *PingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PingResponse proto.InternalMessageInfo

func (m *PingResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type CertificateRenewalNotificationRequest struct {
	// A list of DNS names to monitor for renewals
	DnsNames             []string `protobuf:"bytes,1,rep,name=dnsNames,proto3" json:"dnsNames,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CertificateRenewalNotificationRequest) Reset()         { *m = CertificateRenewalNotificationRequest{} }
func (m *CertificateRenewalNotificationRequest) String() string { return proto.CompactTextString(m) }
func (*CertificateRenewalNotificationRequest) ProtoMessage()    {}
func (*CertificateRenewalNotificationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4}
}

func (m *CertificateRenewalNotificationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CertificateRenewalNotificationRequest.Unmarshal(m, b)
}
func (m *CertificateRenewalNotificationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CertificateRenewalNotificationRequest.Marshal(b, m, deterministic)
}
func (m *CertificateRenewalNotificationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CertificateRenewalNotificationRequest.Merge(m, src)
}
func (m *CertificateRenewalNotificationRequest) XXX_Size() int {
	return xxx_messageInfo_CertificateRenewalNotificationRequest.Size(m)
}
func (m *CertificateRenewalNotificationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CertificateRenewalNotificationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CertificateRenewalNotificationRequest proto.InternalMessageInfo

func (m *CertificateRenewalNotificationRequest) GetDnsNames() []string {
	if m != nil {
		return m.DnsNames
	}
	return nil
}

// Response for a certificate that has been renewed on the server
type RenewedCertificateEvent struct {
	// Example: foo.bar.com
	DnsName              string   `protobuf:"bytes,1,opt,name=dnsName,proto3" json:"dnsName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RenewedCertificateEvent) Reset()         { *m = RenewedCertificateEvent{} }
func (m *RenewedCertificateEvent) String() string { return proto.CompactTextString(m) }
func (*RenewedCertificateEvent) ProtoMessage()    {}
func (*RenewedCertificateEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{5}
}

func (m *RenewedCertificateEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RenewedCertificateEvent.Unmarshal(m, b)
}
func (m *RenewedCertificateEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RenewedCertificateEvent.Marshal(b, m, deterministic)
}
func (m *RenewedCertificateEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RenewedCertificateEvent.Merge(m, src)
}
func (m *RenewedCertificateEvent) XXX_Size() int {
	return xxx_messageInfo_RenewedCertificateEvent.Size(m)
}
func (m *RenewedCertificateEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_RenewedCertificateEvent.DiscardUnknown(m)
}

var xxx_messageInfo_RenewedCertificateEvent proto.InternalMessageInfo

func (m *RenewedCertificateEvent) GetDnsName() string {
	if m != nil {
		return m.DnsName
	}
	return ""
}

func init() {
	proto.RegisterType((*CertificateRequest)(nil), "api.CertificateRequest")
	proto.RegisterType((*CertificateResponse)(nil), "api.CertificateResponse")
	proto.RegisterType((*PingRequest)(nil), "api.PingRequest")
	proto.RegisterType((*PingResponse)(nil), "api.PingResponse")
	proto.RegisterType((*CertificateRenewalNotificationRequest)(nil), "api.CertificateRenewalNotificationRequest")
	proto.RegisterType((*RenewedCertificateEvent)(nil), "api.RenewedCertificateEvent")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 300 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0x6f, 0x4b, 0xc3, 0x30,
	0x10, 0xc6, 0xd7, 0xd5, 0x7f, 0xbd, 0xf9, 0x62, 0x3b, 0x07, 0x0b, 0x45, 0xb4, 0x04, 0x84, 0x21,
	0x58, 0xc4, 0x7d, 0x01, 0x61, 0xf8, 0x42, 0x84, 0x29, 0xfd, 0x06, 0x71, 0x3d, 0x47, 0xc0, 0xa6,
	0xb5, 0xe9, 0x26, 0x7e, 0x65, 0x3f, 0x85, 0x34, 0x4d, 0xb7, 0x8c, 0x32, 0xdf, 0xe5, 0x9e, 0xfc,
	0x72, 0x7d, 0xee, 0xb9, 0x42, 0x20, 0x0a, 0x19, 0x17, 0x65, 0x5e, 0xe5, 0xe8, 0x8b, 0x42, 0xf2,
	0x18, 0x70, 0x4e, 0x65, 0x25, 0x3f, 0xe4, 0x52, 0x54, 0x94, 0xd0, 0xd7, 0x9a, 0x74, 0x85, 0x0c,
	0x4e, 0x53, 0xa5, 0x17, 0x22, 0x23, 0xe6, 0x45, 0xde, 0x34, 0x48, 0xda, 0x92, 0x67, 0x70, 0xb1,
	0xc7, 0xeb, 0x22, 0x57, 0x9a, 0x30, 0x82, 0xc1, 0x72, 0x27, 0xdb, 0x47, 0xae, 0x84, 0x57, 0x00,
	0x45, 0x29, 0x37, 0xa2, 0xa2, 0x17, 0xfa, 0x61, 0x7d, 0x03, 0x38, 0x0a, 0x8e, 0xe1, 0x58, 0x89,
	0x8c, 0x34, 0xf3, 0x23, 0x7f, 0x1a, 0x24, 0x4d, 0xc1, 0xaf, 0x61, 0xf0, 0x26, 0xd5, 0xaa, 0xf5,
	0x35, 0x04, 0x3f, 0xd3, 0x2b, 0xdb, 0xbe, 0x3e, 0xf2, 0x08, 0xce, 0x1b, 0xc0, 0x1a, 0xb1, 0x44,
	0x7f, 0x47, 0xcc, 0xe1, 0x66, 0xcf, 0xb1, 0xa2, 0x6f, 0xf1, 0xb9, 0xc8, 0xad, 0x20, 0x73, 0xd5,
	0x36, 0x0f, 0xe1, 0xcc, 0x4e, 0xa9, 0x99, 0x67, 0x4c, 0x6c, 0x6b, 0x3e, 0x83, 0x89, 0x79, 0x49,
	0xa9, 0xd3, 0xeb, 0x69, 0x43, 0xea, 0x9f, 0xac, 0x1e, 0x7e, 0x3d, 0x18, 0x39, 0xf8, 0xb3, 0xd6,
	0x6b, 0x2a, 0xf1, 0x11, 0x02, 0x73, 0xaa, 0x6f, 0x70, 0x12, 0xd7, 0xfb, 0xe8, 0x6e, 0x20, 0x64,
	0xdd, 0x8b, 0x66, 0x42, 0xde, 0xc3, 0x3b, 0x38, 0xaa, 0x67, 0xc6, 0xa1, 0x61, 0x9c, 0x7c, 0xc2,
	0x91, 0xa3, 0x6c, 0xf1, 0x14, 0xc6, 0xaf, 0xaa, 0x1b, 0x01, 0xde, 0x76, 0x3f, 0x71, 0x28, 0x9b,
	0xf0, 0xd2, 0xb0, 0x07, 0x22, 0xe0, 0xbd, 0x7b, 0xef, 0xfd, 0xc4, 0xfc, 0x54, 0xb3, 0xbf, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xb7, 0x86, 0xa7, 0x99, 0x61, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CertificateIssuerClient is the client API for CertificateIssuer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CertificateIssuerClient interface {
	IssueCert(ctx context.Context, in *CertificateRequest, opts ...grpc.CallOption) (*CertificateResponse, error)
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	OnCertificateRenewal(ctx context.Context, in *CertificateRenewalNotificationRequest, opts ...grpc.CallOption) (CertificateIssuer_OnCertificateRenewalClient, error)
}

type certificateIssuerClient struct {
	cc *grpc.ClientConn
}

func NewCertificateIssuerClient(cc *grpc.ClientConn) CertificateIssuerClient {
	return &certificateIssuerClient{cc}
}

func (c *certificateIssuerClient) IssueCert(ctx context.Context, in *CertificateRequest, opts ...grpc.CallOption) (*CertificateResponse, error) {
	out := new(CertificateResponse)
	err := c.cc.Invoke(ctx, "/api.CertificateIssuer/IssueCert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *certificateIssuerClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, "/api.CertificateIssuer/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *certificateIssuerClient) OnCertificateRenewal(ctx context.Context, in *CertificateRenewalNotificationRequest, opts ...grpc.CallOption) (CertificateIssuer_OnCertificateRenewalClient, error) {
	stream, err := c.cc.NewStream(ctx, &_CertificateIssuer_serviceDesc.Streams[0], "/api.CertificateIssuer/OnCertificateRenewal", opts...)
	if err != nil {
		return nil, err
	}
	x := &certificateIssuerOnCertificateRenewalClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CertificateIssuer_OnCertificateRenewalClient interface {
	Recv() (*RenewedCertificateEvent, error)
	grpc.ClientStream
}

type certificateIssuerOnCertificateRenewalClient struct {
	grpc.ClientStream
}

func (x *certificateIssuerOnCertificateRenewalClient) Recv() (*RenewedCertificateEvent, error) {
	m := new(RenewedCertificateEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CertificateIssuerServer is the server API for CertificateIssuer service.
type CertificateIssuerServer interface {
	IssueCert(context.Context, *CertificateRequest) (*CertificateResponse, error)
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	OnCertificateRenewal(*CertificateRenewalNotificationRequest, CertificateIssuer_OnCertificateRenewalServer) error
}

// UnimplementedCertificateIssuerServer can be embedded to have forward compatible implementations.
type UnimplementedCertificateIssuerServer struct {
}

func (*UnimplementedCertificateIssuerServer) IssueCert(ctx context.Context, req *CertificateRequest) (*CertificateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IssueCert not implemented")
}
func (*UnimplementedCertificateIssuerServer) Ping(ctx context.Context, req *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (*UnimplementedCertificateIssuerServer) OnCertificateRenewal(req *CertificateRenewalNotificationRequest, srv CertificateIssuer_OnCertificateRenewalServer) error {
	return status.Errorf(codes.Unimplemented, "method OnCertificateRenewal not implemented")
}

func RegisterCertificateIssuerServer(s *grpc.Server, srv CertificateIssuerServer) {
	s.RegisterService(&_CertificateIssuer_serviceDesc, srv)
}

func _CertificateIssuer_IssueCert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CertificateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CertificateIssuerServer).IssueCert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.CertificateIssuer/IssueCert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CertificateIssuerServer).IssueCert(ctx, req.(*CertificateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CertificateIssuer_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CertificateIssuerServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.CertificateIssuer/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CertificateIssuerServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CertificateIssuer_OnCertificateRenewal_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CertificateRenewalNotificationRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CertificateIssuerServer).OnCertificateRenewal(m, &certificateIssuerOnCertificateRenewalServer{stream})
}

type CertificateIssuer_OnCertificateRenewalServer interface {
	Send(*RenewedCertificateEvent) error
	grpc.ServerStream
}

type certificateIssuerOnCertificateRenewalServer struct {
	grpc.ServerStream
}

func (x *certificateIssuerOnCertificateRenewalServer) Send(m *RenewedCertificateEvent) error {
	return x.ServerStream.SendMsg(m)
}

var _CertificateIssuer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.CertificateIssuer",
	HandlerType: (*CertificateIssuerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IssueCert",
			Handler:    _CertificateIssuer_IssueCert_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _CertificateIssuer_Ping_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "OnCertificateRenewal",
			Handler:       _CertificateIssuer_OnCertificateRenewal_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api.proto",
}
