// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Request for a certificate to be issued
type CertificateRequest struct {
	// Example: foo.bar.com
	DnsName              string   `protobuf:"bytes,1,opt,name=dnsName,proto3" json:"dnsName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CertificateRequest) Reset()         { *m = CertificateRequest{} }
func (m *CertificateRequest) String() string { return proto.CompactTextString(m) }
func (*CertificateRequest) ProtoMessage()    {}
func (*CertificateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *CertificateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CertificateRequest.Unmarshal(m, b)
}
func (m *CertificateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CertificateRequest.Marshal(b, m, deterministic)
}
func (m *CertificateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CertificateRequest.Merge(m, src)
}
func (m *CertificateRequest) XXX_Size() int {
	return xxx_messageInfo_CertificateRequest.Size(m)
}
func (m *CertificateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CertificateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CertificateRequest proto.InternalMessageInfo

func (m *CertificateRequest) GetDnsName() string {
	if m != nil {
		return m.DnsName
	}
	return ""
}

// A successful response containing a issued certificate
type CertificateResponse struct {
	// A blob containing the cert
	Certificate string `protobuf:"bytes,1,opt,name=certificate,proto3" json:"certificate,omitempty"`
	// A blob containing the private key
	PrivateKey string `protobuf:"bytes,2,opt,name=privateKey,proto3" json:"privateKey,omitempty"`
	// The DNS names this certificate is valid for
	Names                []string `protobuf:"bytes,3,rep,name=names,proto3" json:"names,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CertificateResponse) Reset()         { *m = CertificateResponse{} }
func (m *CertificateResponse) String() string { return proto.CompactTextString(m) }
func (*CertificateResponse) ProtoMessage()    {}
func (*CertificateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *CertificateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CertificateResponse.Unmarshal(m, b)
}
func (m *CertificateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CertificateResponse.Marshal(b, m, deterministic)
}
func (m *CertificateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CertificateResponse.Merge(m, src)
}
func (m *CertificateResponse) XXX_Size() int {
	return xxx_messageInfo_CertificateResponse.Size(m)
}
func (m *CertificateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CertificateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CertificateResponse proto.InternalMessageInfo

func (m *CertificateResponse) GetCertificate() string {
	if m != nil {
		return m.Certificate
	}
	return ""
}

func (m *CertificateResponse) GetPrivateKey() string {
	if m != nil {
		return m.PrivateKey
	}
	return ""
}

func (m *CertificateResponse) GetNames() []string {
	if m != nil {
		return m.Names
	}
	return nil
}

// A request for ping
type PingRequest struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingRequest) Reset()         { *m = PingRequest{} }
func (m *PingRequest) String() string { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()    {}
func (*PingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *PingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingRequest.Unmarshal(m, b)
}
func (m *PingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingRequest.Marshal(b, m, deterministic)
}
func (m *PingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingRequest.Merge(m, src)
}
func (m *PingRequest) XXX_Size() int {
	return xxx_messageInfo_PingRequest.Size(m)
}
func (m *PingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PingRequest proto.InternalMessageInfo

func (m *PingRequest) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

// A response for ping
type PingResponse struct {
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingResponse) Reset()         { *m = PingResponse{} }
func (m *PingResponse) String() string { return proto.CompactTextString(m) }
func (*PingResponse) ProtoMessage()    {}
func (*PingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *PingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingResponse.Unmarshal(m, b)
}
func (m *PingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingResponse.Marshal(b, m, deterministic)
}
func (m *PingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingResponse.Merge(m, src)
}
func (m *PingResponse) XXX_Size() int {
	return xxx_messageInfo_PingResponse.Size(m)
}
func (m *PingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PingResponse proto.InternalMessageInfo

func (m *PingResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*CertificateRequest)(nil), "api.CertificateRequest")
	proto.RegisterType((*CertificateResponse)(nil), "api.CertificateResponse")
	proto.RegisterType((*PingRequest)(nil), "api.PingRequest")
	proto.RegisterType((*PingResponse)(nil), "api.PingResponse")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 234 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0x4f, 0x4b, 0x03, 0x31,
	0x10, 0xc5, 0xdd, 0xae, 0x7f, 0xd8, 0xa9, 0x87, 0x76, 0x14, 0x0c, 0x3d, 0xe8, 0x92, 0x53, 0x2f,
	0xee, 0x41, 0xbf, 0x80, 0xe0, 0x49, 0x04, 0x91, 0xfd, 0x06, 0xb1, 0x8e, 0x25, 0x87, 0x64, 0x63,
	0x26, 0x15, 0xbc, 0xfb, 0xc1, 0x25, 0xd9, 0xac, 0xa6, 0xf4, 0x36, 0xf3, 0xe6, 0x97, 0xbc, 0xc7,
	0x83, 0x46, 0x39, 0xdd, 0x39, 0x3f, 0x84, 0x01, 0x6b, 0xe5, 0xb4, 0xec, 0x00, 0x1f, 0xc9, 0x07,
	0xfd, 0xa1, 0x37, 0x2a, 0x50, 0x4f, 0x9f, 0x3b, 0xe2, 0x80, 0x02, 0xce, 0xde, 0x2d, 0xbf, 0x28,
	0x43, 0xa2, 0x6a, 0xab, 0x75, 0xd3, 0x4f, 0xab, 0x34, 0x70, 0xb1, 0xc7, 0xb3, 0x1b, 0x2c, 0x13,
	0xb6, 0x30, 0xdf, 0xfc, 0xcb, 0xf9, 0x51, 0x29, 0xe1, 0x35, 0x80, 0xf3, 0xfa, 0x4b, 0x05, 0x7a,
	0xa6, 0x6f, 0x31, 0x4b, 0x40, 0xa1, 0xe0, 0x25, 0x9c, 0x58, 0x65, 0x88, 0x45, 0xdd, 0xd6, 0xeb,
	0xa6, 0x1f, 0x17, 0x79, 0x03, 0xf3, 0x57, 0x6d, 0xb7, 0x53, 0xae, 0x05, 0xd4, 0x86, 0xb7, 0xf9,
	0xfb, 0x38, 0xca, 0x16, 0xce, 0x47, 0x20, 0x07, 0xc9, 0xc4, 0xec, 0x8f, 0xb8, 0xfb, 0xa9, 0x60,
	0x59, 0x44, 0x7e, 0x62, 0xde, 0x91, 0xc7, 0x07, 0x68, 0xd2, 0x14, 0x2f, 0x78, 0xd5, 0xc5, 0x56,
	0x0e, 0x7b, 0x58, 0x89, 0xc3, 0xc3, 0xe8, 0x23, 0x8f, 0xf0, 0x16, 0x8e, 0xa3, 0x33, 0x2e, 0x12,
	0x53, 0xa4, 0x5c, 0x2d, 0x0b, 0x65, 0xc2, 0xdf, 0x4e, 0x53, 0xe9, 0xf7, 0xbf, 0x01, 0x00, 0x00,
	0xff, 0xff, 0xb3, 0x12, 0x61, 0x77, 0x81, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CertificateIssuerClient is the client API for CertificateIssuer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CertificateIssuerClient interface {
	IssueCert(ctx context.Context, in *CertificateRequest, opts ...grpc.CallOption) (*CertificateResponse, error)
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
}

type certificateIssuerClient struct {
	cc *grpc.ClientConn
}

func NewCertificateIssuerClient(cc *grpc.ClientConn) CertificateIssuerClient {
	return &certificateIssuerClient{cc}
}

func (c *certificateIssuerClient) IssueCert(ctx context.Context, in *CertificateRequest, opts ...grpc.CallOption) (*CertificateResponse, error) {
	out := new(CertificateResponse)
	err := c.cc.Invoke(ctx, "/api.CertificateIssuer/IssueCert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *certificateIssuerClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, "/api.CertificateIssuer/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CertificateIssuerServer is the server API for CertificateIssuer service.
type CertificateIssuerServer interface {
	IssueCert(context.Context, *CertificateRequest) (*CertificateResponse, error)
	Ping(context.Context, *PingRequest) (*PingResponse, error)
}

func RegisterCertificateIssuerServer(s *grpc.Server, srv CertificateIssuerServer) {
	s.RegisterService(&_CertificateIssuer_serviceDesc, srv)
}

func _CertificateIssuer_IssueCert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CertificateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CertificateIssuerServer).IssueCert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.CertificateIssuer/IssueCert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CertificateIssuerServer).IssueCert(ctx, req.(*CertificateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CertificateIssuer_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CertificateIssuerServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.CertificateIssuer/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CertificateIssuerServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CertificateIssuer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.CertificateIssuer",
	HandlerType: (*CertificateIssuerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IssueCert",
			Handler:    _CertificateIssuer_IssueCert_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _CertificateIssuer_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
